// Massive word bank with 3 progressive hints per word.
// Hints go from vague → specific, helping the Imposter narrow down over the round.

const WORD_BANK = [
  // ── Tiere (Animals) ──
  { category: 'Tiere', word: 'Giraffe', hints: ['Hals', 'Flecken', 'Savanne'] },
  { category: 'Tiere', word: 'Pinguin', hints: ['Schwarz-Weiß', 'Kälte', 'Eis'] },
  { category: 'Tiere', word: 'Delfin', hints: ['Wasser', 'Intelligent', 'Sprung'] },
  { category: 'Tiere', word: 'Fuchs', hints: ['Rot', 'Schlau', 'Wald'] },
  { category: 'Tiere', word: 'Chamäleon', hints: ['Farbe', 'Augen', 'Versteck'] },
  { category: 'Tiere', word: 'Elefant', hints: ['Groß', 'Rüssel', 'Grau'] },
  { category: 'Tiere', word: 'Känguru', hints: ['Springen', 'Beutel', 'Australien'] },
  { category: 'Tiere', word: 'Oktopus', hints: ['Arme', 'Tinte', 'Meer'] },
  { category: 'Tiere', word: 'Igel', hints: ['Stacheln', 'Rollt sich', 'Nacht'] },
  { category: 'Tiere', word: 'Flamingo', hints: ['Rosa', 'Bein', 'See'] },
  { category: 'Tiere', word: 'Eule', hints: ['Nacht', 'Augen', 'Feder'] },
  { category: 'Tiere', word: 'Tintenfisch', hints: ['Tentakel', 'Tinte', 'Tiefsee'] },
  { category: 'Tiere', word: 'Panda', hints: ['Bambus', 'Schwarz-Weiß', 'Frieden'] },
  { category: 'Tiere', word: 'Schnecke', hints: ['Langsam', 'Haus', 'Schleim'] },
  { category: 'Tiere', word: 'Nashorn', hints: ['Horn', 'Dick', 'Afrika'] },
  { category: 'Tiere', word: 'Seepferdchen', hints: ['Klein', 'Wasser', 'Aufrecht'] },
  { category: 'Tiere', word: 'Fledermaus', hints: ['Fliegen', 'Nacht', 'Höhlen'] },
  { category: 'Tiere', word: 'Kakerlake', hints: ['Insekt', 'Ekel', 'Beine'] },
  { category: 'Tiere', word: 'Wal', hints: ['Riesig', 'Blasloch', 'Ozean'] },
  { category: 'Tiere', word: 'Libelle', hints: ['Flügel', 'Wasser', 'Schiller'] },

  // ── Fahrzeuge (Vehicles) ──
  { category: 'Fahrzeuge', word: 'Bagger', hints: ['Schaufel', 'Baugrube', 'Kette'] },
  { category: 'Fahrzeuge', word: 'Heißluftballon', hints: ['Luft', 'Feuer', 'Korb'] },
  { category: 'Fahrzeuge', word: 'U-Boot', hints: ['Unterwasser', 'Periskop', 'Torpedo'] },
  { category: 'Fahrzeuge', word: 'Motorrad', hints: ['Zwei Räder', 'Lenker', 'Helme'] },
  { category: 'Fahrzeuge', word: 'Traktor', hints: ['Feld', 'Reifen', 'Landwirtschaft'] },
  { category: 'Fahrzeuge', word: 'Monster Truck', hints: ['Räder', 'Riesig', 'Rampen'] },
  { category: 'Fahrzeuge', word: 'Feuerwehrauto', hints: ['Rot', 'Leiter', 'Schlauch'] },
  { category: 'Fahrzeuge', word: 'Ambulanz', hints: ['Krankenwagen', 'Sirene', 'Notfall'] },
  { category: 'Fahrzeuge', word: 'Segelflugzeug', hints: ['Flügel', 'Wind', 'Still'] },
  { category: 'Fahrzeuge', word: 'Dampflokomotive', hints: ['Schienen', 'Dampf', 'Pfeife'] },
  { category: 'Fahrzeuge', word: 'Seilbahn', hints: ['Berge', 'Kabine', 'Seil'] },
  { category: 'Fahrzeuge', word: 'Limousine', hints: ['Lang', 'Luxus', 'Chauffeur'] },
  { category: 'Fahrzeuge', word: 'Mülleimerwagen', hints: ['Müll', 'Früh', 'Lärm'] },
  { category: 'Fahrzeuge', word: 'Schneemobil', hints: ['Kufen', 'Eis', 'Motor'] },
  { category: 'Fahrzeuge', word: 'Hubschrauber', hints: ['Rotor', 'Senkrecht', 'Rettung'] },
  { category: 'Fahrzeuge', word: 'Rennwagen', hints: ['Schnell', 'Strecke', 'Aero'] },
  { category: 'Fahrzeuge', word: 'Tuk Tuk', hints: ['Asien', 'Dreirad', 'Lärm'] },
  { category: 'Fahrzeuge', word: 'Rakete', hints: ['Feuer', 'Raum', 'Schub'] },
  { category: 'Fahrzeuge', word: 'Katamaran', hints: ['Zwei Rümpfe', 'Wasser', 'Segel'] },
  { category: 'Fahrzeuge', word: 'Gondel', hints: ['Venedig', 'Wasser', 'Ruder'] },

  // ── Essen (Food) ──
  { category: 'Essen', word: 'Sushi', hints: ['Reis', 'Fisch', 'Rolle'] },
  { category: 'Essen', word: 'Brezel', hints: ['Knoten', 'Salz', 'Laugengebäck'] },
  { category: 'Essen', word: 'Croissant', hints: ['Gebäck', 'Französisch', 'Halbmond'] },
  { category: 'Essen', word: 'Wassermelone', hints: ['Grün', 'Rot', 'Sommer'] },
  { category: 'Essen', word: 'Taco', hints: ['Mais', 'Füllung', 'Mexiko'] },
  { category: 'Essen', word: 'Spaghetti', hints: ['Nudeln', 'Italien', 'Lang'] },
  { category: 'Essen', word: 'Hamburger', hints: ['Brötchen', 'Fleisch', 'USA'] },
  { category: 'Essen', word: 'Pancakes', hints: ['Fladen', 'Sirup', 'Frühstück'] },
  { category: 'Essen', word: 'Döner Kebab', hints: ['Spieß', 'Fleisch', 'Brot'] },
  { category: 'Essen', word: 'Pizza', hints: ['Teig', 'Käse', 'Italien'] },
  { category: 'Essen', word: 'Eiscreme', hints: ['Kalt', 'Waffel', 'Sommer'] },
  { category: 'Essen', word: 'Popcorn', hints: ['Mais', 'Kino', 'Salz'] },
  { category: 'Essen', word: 'Kürbiskuchen', hints: ['Orange', 'Gewürz', 'Herbst'] },
  { category: 'Essen', word: 'Bratwurst', hints: ['Grill', 'Fleisch', 'Würstchen'] },
  { category: 'Essen', word: 'Schokolade', hints: ['Süß', 'Kakao', 'Tafel'] },
  { category: 'Essen', word: 'Ananas', hints: ['Tropen', 'Krone', 'Gelb'] },
  { category: 'Essen', word: 'Kokosnuss', hints: ['Braun', 'Milch', 'Insel'] },
  { category: 'Essen', word: 'Baguette', hints: ['Brot', 'Lang', 'Französisch'] },
  { category: 'Essen', word: 'Frühlingsrolle', hints: ['Knusprig', 'Asien', 'Rolle'] },
  { category: 'Essen', word: 'Zimtschnecke', hints: ['Zimt', 'Schnecke', 'Süß'] },

  // ── Berufe (Professions) ──
  { category: 'Berufe', word: 'Astronaut', hints: ['Raum', 'Anzug', 'Schwerelos'] },
  { category: 'Berufe', word: 'Zauberer', hints: ['Magie', 'Stab', 'Hut'] },
  { category: 'Berufe', word: 'Feuerwehrmann', hints: ['Feuer', 'Axt', 'Retten'] },
  { category: 'Berufe', word: 'Detektiv', hints: ['Lupe', 'Spuren', 'Fall'] },
  { category: 'Berufe', word: 'Koch', hints: ['Küche', 'Messer', 'Hut'] },
  { category: 'Berufe', word: 'Pilot', hints: ['Cockpit', 'Fliegen', 'Uniform'] },
  { category: 'Berufe', word: 'Chirurg', hints: ['Skalpell', 'Maske', 'OP'] },
  { category: 'Berufe', word: 'Bibliothekar', hints: ['Bücher', 'Ruhe', 'Regal'] },
  { category: 'Berufe', word: 'Mechaniker', hints: ['Schraubenschlüssel', 'Auto', 'Werkstatt'] },
  { category: 'Berufe', word: 'Kapitän', hints: ['Schiff', 'Steuerrad', 'Meer'] },
  { category: 'Berufe', word: 'Gärtner', hints: ['Pflanzen', 'Erde', 'Gießen'] },
  { category: 'Berufe', word: 'Tätowierer', hints: ['Nadel', 'Tinte', 'Haut'] },
  { category: 'Berufe', word: 'Bergführer', hints: ['Berge', 'Seil', 'Sicherheit'] },
  { category: 'Berufe', word: 'Perückenmacher', hints: ['Haare', 'Stil', 'Kopf'] },
  { category: 'Berufe', word: 'Imker', hints: ['Bienen', 'Honig', 'Schleier'] },
  { category: 'Berufe', word: 'Uhrmacher', hints: ['Zeiger', 'Zahnrad', 'Präzision'] },
  { category: 'Berufe', word: 'Glaser', hints: ['Fenster', 'Zerbrechlich', 'Heiß'] },
  { category: 'Berufe', word: 'Schausteller', hints: ['Kirmes', 'Bude', 'Jahrmarkt'] },
  { category: 'Berufe', word: 'Dompteur', hints: ['Tiere', 'Peitsche', 'Zirkus'] },
  { category: 'Berufe', word: 'Schatzsucher', hints: ['Karte', 'Gold', 'Abenteuer'] },

  // ── Orte (Places) ──
  { category: 'Orte', word: 'Leuchtturm', hints: ['Licht', 'Küste', 'Stufen'] },
  { category: 'Orte', word: 'Vulkan', hints: ['Lava', 'Ausbruch', 'Berg'] },
  { category: 'Orte', word: 'Burg', hints: ['Mauern', 'Turm', 'Mittelalter'] },
  { category: 'Orte', word: 'Aquarium', hints: ['Fische', 'Glas', 'Wasser'] },
  { category: 'Orte', word: 'Wüste', hints: ['Sand', 'Hitze', 'Oase'] },
  { category: 'Orte', word: 'Pyramide', hints: ['Ägypten', 'Stein', 'Dreieck'] },
  { category: 'Orte', word: 'Wasserfall', hints: ['Höhe', 'Wasser', 'Rauschen'] },
  { category: 'Orte', word: 'Höhle', hints: ['Dunkel', 'Stalaktit', 'Fels'] },
  { category: 'Orte', word: 'Oase', hints: ['Wasser', 'Palmen', 'Wüste'] },
  { category: 'Orte', word: 'Korallenriff', hints: ['Farben', 'Fische', 'Meer'] },
  { category: 'Orte', word: 'Schloss', hints: ['König', 'Zinnen', 'Prunk'] },
  { category: 'Orte', word: 'Iglu', hints: ['Schnee', 'Eis', 'Kuppel'] },
  { category: 'Orte', word: 'Windmühle', hints: ['Flügel', 'Wind', 'Mahlwerk'] },
  { category: 'Orte', word: 'Lehrerzimmer', hints: ['Schule', 'Pause', 'Tische'] },
  { category: 'Orte', word: 'Bibliothek', hints: ['Bücher', 'Stille', 'Regale'] },
  { category: 'Orte', word: 'Tropfsteinhöhle', hints: ['Tropfen', 'Kalk', 'Dunkel'] },
  { category: 'Orte', word: 'Festung', hints: ['Befestigt', 'Mauern', 'Schutz'] },
  { category: 'Orte', word: 'Strand', hints: ['Sand', 'Wellen', 'Sonne'] },
  { category: 'Orte', word: 'Mars', hints: ['Rot', 'Planet', 'Weltraum'] },
  { category: 'Orte', word: 'Treibsand', hints: ['Versinken', 'Sand', 'Gefahr'] },

  // ── Objekte (Objects) ──
  { category: 'Objekte', word: 'Regenschirm', hints: ['Regen', 'Stoff', 'Stab'] },
  { category: 'Objekte', word: 'Kompass', hints: ['Norden', 'Nadel', 'Richtung'] },
  { category: 'Objekte', word: 'Schneekugel', hints: ['Schnee', 'Glas', 'Schütteln'] },
  { category: 'Objekte', word: 'Stethoskop', hints: ['Herz', 'Ohren', 'Arzt'] },
  { category: 'Objekte', word: 'Fernrohr', hints: ['Sterne', 'Linse', 'Auge'] },
  { category: 'Objekte', word: 'Kerze', hints: ['Flamme', 'Wachs', 'Docht'] },
  { category: 'Objekte', word: 'Schneemann', hints: ['Kälte', 'Kohle', 'Karotte'] },
  { category: 'Objekte', word: 'Drachen', hints: ['Wind', 'Faden', 'Himmel'] },
  { category: 'Objekte', word: 'Traubenzucker', hints: ['Energie', 'Trauben', 'Würfel'] },
  { category: 'Objekte', word: 'Kronleuchter', hints: ['Licht', 'Kristall', 'Decke'] },
  { category: 'Objekte', word: 'Puzzle', hints: ['Teile', 'Zusammen', 'Bild'] },
  { category: 'Objekte', word: 'Spieluhr', hints: ['Melodie', 'Drehen', 'Kind'] },
  { category: 'Objekte', word: 'Ventilator', hints: ['Luft', 'Flügel', 'Drehen'] },
  { category: 'Objekte', word: 'Wecker', hints: ['Zeit', 'Klingeln', 'Morgen'] },
  { category: 'Objekte', word: 'Streichholz', hints: ['Feuer', 'Hölzern', 'Reiben'] },
  { category: 'Objekte', word: 'Glühbirne', hints: ['Licht', 'Glas', 'Erfindung'] },
  { category: 'Objekte', word: 'Schlüssel', hints: ['Schloss', 'Zähne', 'Öffnen'] },
  { category: 'Objekte', word: 'Sanduhr', hints: ['Zeit', 'Sand', 'Kippen'] },
  { category: 'Objekte', word: 'Parfümflakon', hints: ['Duft', 'Zerstäuber', 'Glas'] },
  { category: 'Objekte', word: 'Schiffswrack', hints: ['Unterwasser', 'Rost', 'Verloren'] },

  // ── Sport & Freizeit (Sports & Leisure) ──
  { category: 'Sport', word: 'Surfbrett', hints: ['Welle', 'Stehen', 'Flosse'] },
  { category: 'Sport', word: 'Skilift', hints: ['Berge', 'Kälte', 'Sitz'] },
  { category: 'Sport', word: 'Boxhandschuh', hints: ['Faust', 'Ring', 'Rot'] },
  { category: 'Sport', word: 'Bumerang', hints: ['Werfen', 'Zurück', 'Holz'] },
  { category: 'Sport', word: 'Slackline', hints: ['Band', 'Balancieren', 'Baum'] },
  { category: 'Sport', word: 'Paintballmarkierer', hints: ['Farbe', 'Schießen', 'Maske'] },
  { category: 'Sport', word: 'Klettergurt', hints: ['Seil', 'Sicherheit', 'Hüfte'] },
  { category: 'Sport', word: 'Bogenschießen', hints: ['Pfeil', 'Bogen', 'Ziel'] },
  { category: 'Sport', word: 'Eishockeyschläger', hints: ['Eis', 'Puck', 'Kurve'] },
  { category: 'Sport', word: 'Trapez', hints: ['Zirkus', 'Schwingen', 'Höhe'] },

  // ── Natur (Nature) ──
  { category: 'Natur', word: 'Regenbogen', hints: ['Farben', 'Bogen', 'Regen'] },
  { category: 'Natur', word: 'Schneeflocke', hints: ['Kalt', 'Kristall', 'Einzigartig'] },
  { category: 'Natur', word: 'Blitz', hints: ['Strom', 'Himmel', 'Schnell'] },
  { category: 'Natur', word: 'Pilz', hints: ['Hut', 'Stiel', 'Wald'] },
  { category: 'Natur', word: 'Sonnenblume', hints: ['Gelb', 'Kern', 'Sonnen'] },
  { category: 'Natur', word: 'Kaktus', hints: ['Stacheln', 'Wüste', 'Wasser'] },
  { category: 'Natur', word: 'Mondkrater', hints: ['Loch', 'Mond', 'Einschlag'] },
  { category: 'Natur', word: 'Gletscher', hints: ['Eis', 'Berg', 'Fließen'] },
  { category: 'Natur', word: 'Aurora', hints: ['Polarlicht', 'Farben', 'Himmel'] },
  { category: 'Natur', word: 'Fata Morgana', hints: ['Trugbild', 'Hitze', 'Wüste'] },

  // ── Gebäude & Architektur (Architecture) ──
  { category: 'Architektur', word: 'Brücke', hints: ['Verbindung', 'Stahl', 'Spann'] },
  { category: 'Architektur', word: 'Wolkenkratzer', hints: ['Hoch', 'Glas', 'Stadt'] },
  { category: 'Architektur', word: 'Pagode', hints: ['Asien', 'Etagen', 'Dach'] },
  { category: 'Architektur', word: 'Säulentempel', hints: ['Säulen', 'Antike', 'Griechisch'] },
  { category: 'Architektur', word: 'Kuppeldach', hints: ['Rund', 'Gewölbe', 'Spitze'] },
  { category: 'Architektur', word: 'Fachwerkhaus', hints: ['Holz', 'Fach', 'Deutsch'] },
  { category: 'Architektur', word: 'Torburg', hints: ['Tor', 'Mauer', 'Durchlass'] },
  { category: 'Architektur', word: 'Hängebrücke', hints: ['Seile', 'Tiefe', 'Schwung'] },
  { category: 'Architektur', word: 'Kirchturm', hints: ['Glocke', 'Spitze', 'Dorf'] },
  { category: 'Architektur', word: 'Stadttor', hints: ['Mauer', 'Durchgang', 'Wappen'] },

  // ── Fantasy & Mythologie (Fantasy) ──
  { category: 'Fantasy', word: 'Einhorn', hints: ['Horn', 'Weiß', 'Magie'] },
  { category: 'Fantasy', word: 'Drache', hints: ['Feuer', 'Flügel', 'Schuppen'] },
  { category: 'Fantasy', word: 'Phönix', hints: ['Feuer', 'Wiedergeburt', 'Vogel'] },
  { category: 'Fantasy', word: 'Greif', hints: ['Adler', 'Löwe', 'Flügel'] },
  { category: 'Fantasy', word: 'Kobold', hints: ['Klein', 'Schabernack', 'Höhle'] },
  { category: 'Fantasy', word: 'Zentaur', hints: ['Pferd', 'Mensch', 'Bogen'] },
  { category: 'Fantasy', word: 'Meerjungfrau', hints: ['Fischschwanz', 'Schönheit', 'Meer'] },
  { category: 'Fantasy', word: 'Riese', hints: ['Groß', 'Stark', 'Märchen'] },
  { category: 'Fantasy', word: 'Troll', hints: ['Brücke', 'Hässlich', 'Nacht'] },
  { category: 'Fantasy', word: 'Weihnachtsmann', hints: ['Rot', 'Geschenke', 'Schlitten'] },

  // ── Tiere: Erweiterung ──
  { category: 'Tiere', word: 'Ameise', hints: ['Insekt', 'Organisiert', 'Stark'] },
  { category: 'Tiere', word: 'Biber', hints: ['Damm', 'Schwanz', 'Nager'] },
  { category: 'Tiere', word: 'Dachs', hints: ['Gräber', 'Schwarz-Weiß', 'Nacht'] },
  { category: 'Tiere', word: 'Eisbär', hints: ['Weiß', 'Arktis', 'Kälte'] },
  { category: 'Tiere', word: 'Faultier', hints: ['Langsam', 'Baum', 'Hängend'] },
  { category: 'Tiere', word: 'Grashüpfer', hints: ['Springen', 'Beine', 'Wiese'] },
  { category: 'Tiere', word: 'Hai', hints: ['Zähne', 'Meer', 'Rückenflosse'] },
  { category: 'Tiere', word: 'Krokodil', hints: ['Zähne', 'Sumpf', 'Panzer'] },
  { category: 'Tiere', word: 'Maulwurf', hints: ['Untergrund', 'Gräbt', 'Blind'] },
  { category: 'Tiere', word: 'Pfau', hints: ['Rad', 'Feder', 'Farben'] },
  { category: 'Tiere', word: 'Raupe', hints: ['Kriecht', 'Schmetterling', 'Beine'] },
  { category: 'Tiere', word: 'Seelöwe', hints: ['Bellen', 'Flossen', 'Küste'] },
  { category: 'Tiere', word: 'Storch', hints: ['Schnabel', 'Nest', 'Baby'] },
  { category: 'Tiere', word: 'Tausendfüßler', hints: ['Beine', 'Kriecht', 'Rollen'] },
  { category: 'Tiere', word: 'Zikade', hints: ['Summen', 'Flügel', 'Baum'] },

  // ── Fahrzeuge: Erweiterung ──
  { category: 'Fahrzeuge', word: 'Bulldozer', hints: ['Schieben', 'Raupen', 'Bau'] },
  { category: 'Fahrzeuge', word: 'Pferd', hints: ['Reittier', 'Sattel', 'Galopp'] },
  { category: 'Fahrzeuge', word: 'E-Scooter', hints: ['Elektrisch', 'Stehend', 'Stadt'] },
  { category: 'Fahrzeuge', word: 'Pferdekutsche', hints: ['Pferde', 'Räder', 'Früher'] },
  { category: 'Fahrzeuge', word: 'Schlitten', hints: ['Schnee', 'Kufen', 'Winter'] },
  { category: 'Fahrzeuge', word: 'Straßenbahn', hints: ['Schienen', 'Stadt', 'Strom'] },
  { category: 'Fahrzeuge', word: 'Mofa', hints: ['Motor', 'Fahrrad', 'Klein'] },
  { category: 'Fahrzeuge', word: 'Hecklader', hints: ['Müll', 'Hinten', 'Lift'] },
  { category: 'Fahrzeuge', word: 'Golfmobil', hints: ['Platz', 'Akku', 'Klein'] },
  { category: 'Fahrzeuge', word: 'Waggong', hints: ['Schienen', 'Zug', 'Güter'] },

  // ── Essen: Erweiterung ──
  { category: 'Essen', word: 'Currywurst', hints: ['Wurst', 'Soße', 'Berlin'] },
  { category: 'Essen', word: 'Maultasche', hints: ['Teigtasche', 'Schwaben', 'Füllung'] },
  { category: 'Essen', word: 'Kaiserschmarrn', hints: ['Süß', 'Zerrissen', 'Österreich'] },
  { category: 'Essen', word: 'Raclette', hints: ['Käse', 'Schmelzen', 'Winter'] },
  { category: 'Essen', word: 'Fondue', hints: ['Käse', 'Topf', 'Spießen'] },
  { category: 'Essen', word: 'Crème Brûlée', hints: ['Creme', 'Karamell', 'Französisch'] },
  { category: 'Essen', word: 'Mango', hints: ['Tropen', 'Orange', 'Stein'] },
  { category: 'Essen', word: 'Marzipan', hints: ['Mandel', 'Süß', 'Lübeck'] },
  { category: 'Essen', word: 'Pretzel', hints: ['Knoten', 'Lauge', 'Salz'] },
  { category: 'Essen', word: 'Tiramisu', hints: ['Kaffee', 'Italien', 'Schicht'] },

  // ── Berufe: Erweiterung ──
  { category: 'Berufe', word: 'Bäcker', hints: ['Brot', 'Ofen', 'Morgen'] },
  { category: 'Berufe', word: 'Metzger', hints: ['Fleisch', 'Wurst', 'Messer'] },
  { category: 'Berufe', word: 'Zahnarzt', hints: ['Zähne', 'Bohrer', 'Stuhl'] },
  { category: 'Berufe', word: 'Friseur', hints: ['Haare', 'Schere', 'Stuhl'] },
  { category: 'Berufe', word: 'Maurer', hints: ['Steine', 'Mörtel', 'Mauer'] },
  { category: 'Berufe', word: 'Dachdecker', hints: ['Dach', 'Leiter', 'Höhe'] },
  { category: 'Berufe', word: 'Bestatter', hints: ['Tod', 'Sarg', 'Trauer'] },
  { category: 'Berufe', word: 'Kürschner', hints: ['Pelz', 'Fell', 'Mantel'] },
  { category: 'Berufe', word: 'Steinmetz', hints: ['Stein', 'Meißel', 'Skulptur'] },
  { category: 'Berufe', word: 'Notar', hints: ['Urkunde', 'Stempel', 'Vertrag'] },

  // ── Orte: Erweiterung ──
  { category: 'Orte', word: 'Marktplatz', hints: ['Brunnen', 'Stadt', 'Treffen'] },
  { category: 'Orte', word: 'Bahnhof', hints: ['Züge', 'Gleise', 'Reise'] },
  { category: 'Orte', word: 'Friedhof', hints: ['Gräber', 'Stille', 'Trauer'] },
  { category: 'Orte', word: 'Freibad', hints: ['Schwimmen', 'Sommer', 'Becken'] },
  { category: 'Orte', word: 'Krankenhaus', hints: ['Kranke', 'Weiß', 'Notaufnahme'] },
  { category: 'Orte', word: 'Rathaus', hints: ['Bürgermeister', 'Standesamt', 'Stadt'] },
  { category: 'Orte', word: 'Stadion', hints: ['Sport', 'Tribüne', 'Rund'] },
  { category: 'Orte', word: 'Hafen', hints: ['Schiffe', 'Kran', 'Container'] },
  { category: 'Orte', word: 'Kirmes', hints: ['Karussell', 'Buden', 'Jahrmarkt'] },
  { category: 'Orte', word: 'Bauernhof', hints: ['Tiere', 'Feld', 'Scheune'] },

  // ── Objekte: Erweiterung ──
  { category: 'Objekte', word: 'Briefmarke', hints: ['Post', 'Kleber', 'Zähnung'] },
  { category: 'Objekte', word: 'Korkenzieher', hints: ['Korken', 'Drehen', 'Wein'] },
  { category: 'Objekte', word: 'Schneeschuh', hints: ['Schnee', 'Laufen', 'Breit'] },
  { category: 'Objekte', word: 'Federboa', hints: ['Federn', 'Tanz', 'Lang'] },
  { category: 'Objekte', word: 'Kaffeemühle', hints: ['Bohnen', 'Drehen', 'Pulver'] },
  { category: 'Objekte', word: 'Nussknacker', hints: ['Nüsse', 'Kiefer', 'Holz'] },
  { category: 'Objekte', word: 'Dosenöffner', hints: ['Dose', 'Schneiden', 'Küche'] },
  { category: 'Objekte', word: 'Kleiderbügel', hints: ['Kleidung', 'Schrank', 'Haken'] },
  { category: 'Objekte', word: 'Schuhlöffel', hints: ['Schuh', 'Fuß', 'Hinein'] },
  { category: 'Objekte', word: 'Schirm', hints: ['Regen', 'Stoff', 'Stab'] },

  // ── Sport: Erweiterung ──
  { category: 'Sport', word: 'Frisbee', hints: ['Werfen', 'Scheibe', 'Fliegen'] },
  { category: 'Sport', word: 'Jonglierball', hints: ['Werfen', 'Fangen', 'Drei'] },
  { category: 'Sport', word: 'Hula-Hoop-Reifen', hints: ['Hüfte', 'Kreisen', 'Plastik'] },
  { category: 'Sport', word: 'Diabolo', hints: ['Stöcke', 'Spinnen', 'Werfen'] },
  { category: 'Sport', word: 'Pogo-Stick', hints: ['Springen', 'Stange', 'Aufrecht'] },

  // ── Natur: Erweiterung ──
  { category: 'Natur', word: 'Morserschlucht', hints: ['Klamm', 'Wasser', 'Eng'] },
  { category: 'Natur', word: 'Geysir', hints: ['Wasser', 'Ausbruch', 'Heiß'] },
  { category: 'Natur', word: 'Koralleninsel', hints: ['Atoll', 'Riff', 'Sand'] },
  { category: 'Natur', word: 'Mondfinsternis', hints: ['Schatten', 'Erde', 'Rot'] },
  { category: 'Natur', word: 'Stalagmit', hints: ['Höhle', 'Wächst', 'Boden'] },

  // ── Architektur: Erweiterung ──
  { category: 'Architektur', word: 'Burggraben', hints: ['Wasser', 'Brücke', 'Schutz'] },
  { category: 'Architektur', word: 'Zinnen', hints: ['Mauer', 'Zacken', 'Oben'] },
  { category: 'Architektur', word: 'Turmspitze', hints: ['Oben', 'Spitz', 'Turm'] },
  { category: 'Architektur', word: 'Bogenfenster', hints: ['Rund', 'Fenster', 'Bogen'] },
  { category: 'Architektur', word: 'Stützbogen', hints: ['Stützen', 'Bogen', 'Mauer'] },

  // ── Fantasy: Erweiterung ──
  { category: 'Fantasy', word: 'Witch', hints: ['Hexe', 'Besen', 'Kessel'] },
  { category: 'Fantasy', word: 'Vampir', hints: ['Blut', 'Fledermaus', 'Nacht'] },
  { category: 'Fantasy', word: 'Werwolf', hints: ['Wolf', 'Mond', 'Verwandlung'] },
  { category: 'Fantasy', word: 'Geist', hints: ['Tot', 'Durchsichtig', 'Spuk'] },
  { category: 'Fantasy', word: 'Golem', hints: ['Ton', 'Lehm', 'Beschützt'] }
];

module.exports = WORD_BANK;
